"""Run the probes' collectors against a fake /proc, /sys and /dev tree, with
every external command stubbed, so the sysfs-walking code is exercised
without a Pi (and without sudo)."""

from __future__ import annotations

import struct

import pytest

from rpi_hwid import fpga, probe


def _w(root, rel, content):
    path = root / rel.lstrip("/")
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content)
    return path


def _pi5_tree(root):
    _w(root, "/proc/device-tree/model", "Raspberry Pi 5 Model B Rev 1.1\0")
    _w(root, "/proc/device-tree/compatible", "raspberrypi,5-model-b\0brcm,bcm2712\0")
    _w(root, "/proc/device-tree/serial-number", "c36b093f773d46b8\0")
    _w(root, "/proc/meminfo", "MemTotal:        1006740 kB\n")
    _w(root, "/proc/cpuinfo", "processor\t: 0\nRevision\t: a04171\nSerial\t\t: c36b093f773d46b8\n")
    _w(root, "/proc/device-tree/chosen/power/max_current", struct.pack(">I", 3000))
    _w(root, "/proc/device-tree/chosen/power/usbpd_power_data_objects", b"\0" * 28)
    _w(root, "/proc/device-tree/cooling_fan/status", "okay\0")
    _w(root, "/sys/class/hwmon/hwmon2/name", "pwmfan\n")
    _w(root, "/sys/class/hwmon/hwmon2/fan1_input", "2471\n")
    # onboard ethernet (macb) and a Realtek dongle on usb 2-1
    _w(root, "/sys/class/net/eth0/address", "98:fe:54:13:f5:75\n")
    _w(root, "/sys/class/net/eth0/speed", "1000\n")
    (root / "sys/class/net/eth0/device").mkdir(parents=True)
    _w(root, "/sys/devices/platform/axi/1000120000.pcie/1f00100000.ethernet/x", "")
    (root / "sys/class/net/eth0/device/driver").symlink_to(
        root / "sys/bus/platform/drivers/macb")
    (root / "sys/bus/platform/drivers/macb").mkdir(parents=True)
    _w(root, "/sys/class/net/eth1/address", "00:e0:4c:68:01:03\n")
    _w(root, "/sys/class/net/eth1/speed", "100\n")
    dev = root / ("sys/devices/platform/axi/1000120000.pcie/1f00200000.usb/"
                  "xhci-hcd.0/usb2/2-1/2-1:1.0")
    dev.mkdir(parents=True)
    (root / "sys/class/net/eth1/device").symlink_to(dev)
    (root / "sys/bus/usb/drivers/r8152").mkdir(parents=True)
    (dev / "driver").symlink_to(root / "sys/bus/usb/drivers/r8152")
    for k, v in (("idVendor", "0bda"), ("idProduct", "8153"), ("manufacturer", "Realtek"),
                 ("product", "USB 10/100/1000 LAN"), ("serial", "001000001"),
                 ("version", " 3.00"), ("speed", "5000")):
        _w(root, "/sys/bus/usb/devices/2-1/" + k, v + "\n")
    _w(root, "/sys/bus/usb/devices/usb2/idVendor", "1d6b\n")
    _w(root, "/sys/bus/usb/devices/usb2/idProduct", "0003\n")
    # the Acorn on PCIe, plus the RP1 which is not a board
    for slot, vend, dev_id, cls, res, sub in (
        ("0001:01:00.0", "0x1e24", "0x021f", "0x120000",
         "0x1b00000000 0x1b0001ffff 0x40200\n0x1b00100000 0x1b0010ffff 0x40200\n0 0 0\n",
         ("0x1e24", "0x021f")),
        ("0000:01:00.0", "0x1de4", "0x0001", "0x020000",
         "0x1f00000000 0x1f00003fff 0x40200\n0x1f00400000 0x1f007fffff 0x40200\n",
         ("0x1de4", "0x0001")),
        ("0001:00:00.0", "0x14e4", "0x2712", "0x060400", "", ("0x0000", "0x0000")),
    ):
        _w(root, f"/sys/bus/pci/devices/{slot}/vendor", vend + "\n")
        _w(root, f"/sys/bus/pci/devices/{slot}/device", dev_id + "\n")
        _w(root, f"/sys/bus/pci/devices/{slot}/class", cls + "\n")
        _w(root, f"/sys/bus/pci/devices/{slot}/resource", res)
        _w(root, f"/sys/bus/pci/devices/{slot}/subsystem_vendor", sub[0] + "\n")
        _w(root, f"/sys/bus/pci/devices/{slot}/subsystem_device", sub[1] + "\n")


def _orange_pi_pc_tree(root):
    """An Orange Pi PC on Armbian trixie, as captured from opi1pc-b on
    2026-07-08: the device tree U-Boot hands the kernel (model, compatible,
    the serial# it built from the SID), the 32-bit kernel's cpuinfo (which
    repeats that serial and prints a meaningless Revision), MemTotal, the
    Armbian release file, the sunxi-sid nvmem, the H3's EMAC on
    dwmac-sun8i, and the CDC-ECM gadget interface. The SID words 1-3 are
    chosen so U-Boot's CRC-32 rule lands on the captured serial (the real
    words were never read; the board is off the network)."""
    _w(root, "/proc/device-tree/model", "Xunlong Orange Pi PC\0")
    _w(root, "/proc/device-tree/compatible", "xunlong,orangepi-pc\0allwinner,sun8i-h3\0")
    _w(root, "/proc/device-tree/serial-number", "02c00181e1ce7d46\0")
    _w(root, "/proc/cpuinfo",
       "processor\t: 0\nmodel name\t: ARMv7 Processor rev 5 (v7l)\nCPU part\t: 0xc07\n"
       "Hardware\t: Allwinner sun8i Family\nRevision\t: 0000\nSerial\t\t: 02c00181e1ce7d46\n")
    _w(root, "/proc/meminfo", "MemTotal:        1015636 kB\nMemFree:          612340 kB\n")
    _w(root, "/etc/armbian-release",
       "# PLEASE DO NOT EDIT THIS FILE\nBOARD=orangepipc\nBOARD_NAME=\"Orange Pi PC\"\n"
       "BOARDFAMILY=sun8i\nLINUXFAMILY=sunxi\nARCH=arm\nBOARD_TYPE=csc\nBRANCH=current\n"
       "VERSION=26.8.0-trunk.170\n")
    _w(root, "/sys/bus/nvmem/devices/sunxi-sid0/nvmem",
       bytes.fromhex("8101c0025f4a0b0c9e8c1e8c274e02f8") + b"\0" * 240)
    _w(root, "/sys/class/net/eth0/address", "02:81:e1:ce:7d:46\n")
    _w(root, "/sys/class/net/eth0/speed", "100\n")
    emac = root / "sys/devices/platform/soc/1c30000.ethernet"
    emac.mkdir(parents=True)
    (root / "sys/class/net/eth0/device").symlink_to(emac)
    (root / "sys/bus/platform/drivers/dwmac-sun8i").mkdir(parents=True)
    (emac / "driver").symlink_to(root / "sys/bus/platform/drivers/dwmac-sun8i")
    _w(root, "/sys/class/net/usb0/address", "aa:8f:2b:0c:11:3e\n")
    gadget = root / "sys/devices/platform/soc/1c19000.usb/musb-hdrc.2.auto/gadget.0"
    gadget.mkdir(parents=True)
    (root / "sys/class/net/usb0/device").symlink_to(gadget)
    _w(root, "/sys/bus/usb/devices/usb1/idVendor", "1d6b\n")
    _w(root, "/sys/bus/usb/devices/usb1/idProduct", "0002\n")


@pytest.fixture
def opi_root(tmp_path, monkeypatch):
    _orange_pi_pc_tree(tmp_path)
    monkeypatch.setattr(probe, "ROOT", str(tmp_path))
    calls = []

    def fake_sh(args, timeout=15):
        calls.append(args)
        return ""
    monkeypatch.setattr(probe, "sh", fake_sh)
    return tmp_path, calls


def test_collect_orange_pi_pc(opi_root):
    _root, calls = opi_root
    d = probe.collect()
    assert d["board"] == "opi"
    assert d["model"] == "Xunlong Orange Pi PC"
    assert d["compatible"] == ["xunlong,orangepi-pc", "allwinner,sun8i-h3"]
    assert d["serial"] == "02c00181e1ce7d46"
    assert d["cpuinfo_serial"] == "02c00181e1ce7d46"
    assert d["sid"] == ["0x02c00181", "0x0c0b4a5f", "0x8c1e8c9e", "0xf8024e27"]
    assert d["sid_serial"] == "02c00181e1ce7d46", "U-Boot's rule reproduces the DT serial"
    assert d["revision"] is None, "cpuinfo's 0000 is not a revision code"
    assert d["mem_kb"] == 1015636
    assert d["armbian"]["VERSION"] == "26.8.0-trunk.170"
    assert d["armbian"]["BOARD_NAME"] == "Orange Pi PC"
    assert d["hat_fw"] is None
    assert d["hat_eeproms"] == {}
    assert d["i2c1"] is None
    assert d["throttled"] is None
    assert d["pi5"] is False
    assert calls == [], "no sudo, dtparam, i2cdetect or vcgencmd on a board without them"
    ifaces = {i["name"]: i for i in d["interfaces"]}
    assert ifaces["eth0"]["onboard"] is True
    assert ifaces["eth0"]["driver"] == "dwmac-sun8i"
    assert ifaces["eth0"]["kind"] == "eth"
    assert ifaces["usb0"]["onboard"] is False
    assert ifaces["usb0"]["kind"] == "other"
    assert ifaces["usb0"]["usb"] is None, "a gadget is not a USB device on the host side"
    assert d["usb_net"] == []
    v = probe.verdict(d)
    assert v["header"] == ["40-pin header not probed: no HAT ID EEPROM convention on this board"]
    assert "no power sensing" in v["power"]
    assert any(e.startswith("Allwinner SID 0x02c00181") for e in v["evidence"])
    assert any(e.startswith("Armbian 26.8.0-trunk.170 on board id orangepipc")
               for e in v["evidence"])
    s = v["summary"]
    assert s["model"] == "Xunlong Orange Pi PC"
    assert s["serial"] == "02c00181e1ce7d46"
    assert s["revision"] is None
    assert s["compatible"] == "xunlong,orangepi-pc allwinner,sun8i-h3"
    assert s["memory"] == "1 GB"
    assert s["header"] == []
    assert s["hat_uuid"] is None
    assert s["power_class"] == "undetermined"
    assert s["macs"] == [{"kind": "eth", "mac": "02:81:e1:ce:7d:46"}]
    assert s["usb_net"] == []
    assert s["rtc_battery"] is None
    assert s["fan"] is None
    assert s["max_current_ma"] is None
    assert s["ext5v_v"] is None


def test_orange_pi_serial_falls_back_to_the_sid(opi_root):
    """A device tree without /serial-number and a cpuinfo Serial of zeros
    (an older U-Boot) leave the SID as the only source."""
    root, _calls = opi_root
    (root / "proc/device-tree/serial-number").unlink()
    _w(root, "/proc/cpuinfo", "Hardware\t: Allwinner sun8i Family\nRevision\t: 0000\n"
                              "Serial\t\t: 0000000000000000\n")
    d = probe.collect()
    assert d["serial"] == "02c00181e1ce7d46"
    assert d["cpuinfo_serial"] == "0000000000000000"
    v = probe.verdict(d)
    assert v["summary"]["serial"] == "02c00181e1ce7d46"
    assert probe.headline(d) == "Xunlong Orange Pi PC  serial 02c00181e1ce7d46"


@pytest.mark.parametrize(("kb", "want"), [
    (None, None), (1015636, "1 GB"), (443212, "512 MB"), (4143120, "4 GB"),
    (8167424, "8 GB"), (16523456, "16 GB"), (31171676, "32 GB"), (70000000, "67 GB"),
])
def test_nominal_memory(kb, want):
    assert probe.nominal_memory(kb) == want


def test_board_kind():
    assert probe.board_kind("Raspberry Pi 5 Model B Rev 1.0",
                            ["raspberrypi,5-model-b", "brcm,bcm2712"]) == "rpi"
    assert probe.board_kind("Raspberry Pi Zero W Rev 1.1", []) == "rpi"
    assert probe.board_kind("Xunlong Orange Pi PC",
                            ["xunlong,orangepi-pc", "allwinner,sun8i-h3"]) == "opi"
    assert probe.board_kind("", ["xunlong,orangepi-zero", "allwinner,sun8i-h2-plus"]) == "opi"
    assert probe.board_kind("MinnowBoard Turbot", []) == "other"


@pytest.fixture
def fake_root(tmp_path, monkeypatch):
    _pi5_tree(tmp_path)
    monkeypatch.setattr(probe, "ROOT", str(tmp_path))
    monkeypatch.setattr(fpga, "ROOT", str(tmp_path))
    # no sudo, no vcgencmd, no openFPGALoader here: every command answers
    # what it would on a machine lacking the tool, and the PMIC line is fed
    # by the one stub that matters
    def fake_sh(args, timeout=15):
        if args[:2] == ["sudo", "vcgencmd"]:
            return ("EXT5V_V volt(24)=5.33990000V\nBATT_V volt(25)=3.26000000V\n")
        if args == ["vcgencmd", "get_throttled"]:
            return "throttled=0x0"
        return ""
    monkeypatch.setattr(probe, "sh", fake_sh)
    monkeypatch.setattr(fpga, "sh", fake_sh)
    return tmp_path


def test_collect_walks_the_tree(fake_root):
    d = probe.collect()
    assert d["model"] == "Raspberry Pi 5 Model B Rev 1.1"
    assert d["board"] == "rpi"
    assert d["serial"] == "c36b093f773d46b8"
    assert d["revision"] == "a04171"
    assert d["sid"] is None
    assert d["pi5"] is True
    assert d["max_current_ma"] == 3000
    assert d["usbpd_pdos"] == []
    assert d["ext5v_v"] == pytest.approx(5.3399)
    assert d["rtc_batt_v"] == pytest.approx(3.26)
    assert d["fan_dt"] == "okay"
    assert d["fan_rpm"] == 2471
    assert d["hat_fw"] is None
    assert d["hat_eeproms"] == {}
    assert d["i2c1"] is None
    assert d["throttled"] == "0x0"
    ifaces = {i["name"]: i for i in d["interfaces"]}
    assert ifaces["eth0"]["onboard"] is True
    assert ifaces["eth0"]["driver"] == "macb"
    assert ifaces["eth1"]["onboard"] is False
    assert ifaces["eth1"]["usb"] == "2-1"
    (adapter,) = d["usb_net"]
    assert adapter["vidpid"] == "0bda:8153"
    assert adapter["bcd_usb"] == "3.00"
    assert adapter["kind"] == "ethernet"
    v = probe.verdict(d)
    assert v["summary"]["macs"] == [{"kind": "eth", "mac": "98:fe:54:13:f5:75"}]
    assert v["summary"]["power_class"] == "ambiguous"
    assert v["summary"]["rtc_battery"] is True
    assert v["summary"]["compatible"] == "raspberrypi,5-model-b brcm,bcm2712"
    assert v["summary"]["memory"] == "1 GB"


def test_fpga_collect_finds_the_acorn_not_the_rp1(fake_root):
    f = fpga.collect_fpga()
    ids = {p["id"]: p for p in f["pcie"]}
    assert "1e24:021f" in ids
    assert ids["1e24:021f"]["bars"] == [128 << 10, 64 << 10]
    assert "14e4:2712" not in ids, "the root port is a bridge, not an endpoint"
    assert f["boards"][0]["kind"] == "acorn"
    assert f["summary"] == [{"kind": "acorn"}]
    assert f["jtag"] is None


def test_fpga_jtag_without_tool_is_an_error_record(fake_root):
    f = fpga.collect_fpga(jtag=True)
    assert f["jtag"] == {"error": "openFPGALoader not installed"}


def test_merge_fpga_into_probe_document(fake_root):
    d = probe.collect()
    d["verdict"] = probe.verdict(d)
    fpga.merge_fpga(d, fpga.collect_fpga())
    assert d["verdict"]["summary"]["fpga"] == [{"kind": "acorn"}]
    assert d["fpga"]["pcie"]


def test_hat_firmware_dir_and_id_bus(fake_root, monkeypatch):
    for k, v in (("vendor", "Digilent"), ("product", "Pmod HAT Adaptor"),
                 ("product_id", "0x0001"), ("product_ver", "0x0001"),
                 ("uuid", "6bcd3833-3d1d-4b3e-9ab1-945c71845f3a")):
        _w(fake_root, "/proc/device-tree/hat/" + k, v + "\0")
    _w(fake_root, "/dev/i2c-1", "")
    _w(fake_root, "/dev/i2c-0", "")
    i2cdetect = ("     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f\n"
                 "00:                         -- -- -- -- -- -- -- --\n"
                 "20: 20 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --\n"
                 "30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- --\n")

    def fake_sh(args, timeout=15):
        if args[:3] == ["sudo", "i2cdetect", "-y"]:
            return i2cdetect
        if args[:2] == ["sudo", "i2ctransfer"]:
            return ""       # no EEPROM answers on the ID bus
        if args == ["vcgencmd", "get_throttled"]:
            return "throttled=0x10000"
        return ""
    monkeypatch.setattr(probe, "sh", fake_sh)
    d = probe.collect()
    assert d["hat_fw"]["product"] == "Pmod HAT Adaptor"
    assert d["i2c1"] == ["20", "3c"]
    assert d["undervoltage_since_boot"] is True
    v = probe.verdict(d)
    assert "Digilent Pmod HAT Adaptor" in v["summary"]["header"]
    assert "Waveshare PoE HAT (B)" in v["summary"]["header"]
    assert v["summary"]["hat_uuid"] == "6bcd3833-3d1d-4b3e-9ab1-945c71845f3a"


def test_probe_main_prints_text_and_json(fake_root, capsys, monkeypatch):
    monkeypatch.setattr("sys.argv", ["probe.py"])
    probe.main()
    out = capsys.readouterr().out
    assert "power  :" in out
    assert "onboard: eth" in out
    monkeypatch.setattr("sys.argv", ["probe.py", "--json"])
    probe.main()
    assert '"verdict"' in capsys.readouterr().out
    monkeypatch.setattr("sys.argv", ["fpga.py"])
    fpga.main()
    assert "acorn" in capsys.readouterr().out
