"""The Tiny Tapeout board colours, from the published spreadsheet.

``tt_boards.json`` beside this module is generated by
``tools/fetch_tt_boards.py`` out of two sheets: one row per tapeout for the
chip carrier, one row per demo board revision with the shuttles that board
serves. CI re-derives it and fails when the sheet has moved, so the file is
the sheet as of the last commit rather than a copy that quietly rots.

What a label needs is per shuttle, so ``shuttle_boards()`` does the join the
sheets do not: a shuttle's carrier is its own row, and its demo board is
whichever board lists the shuttle in "Used by".

The hex is the sheet's, measured off the boards, rather than the one name
per colour ``tinytapeout.COLOURS`` holds: TT06's pink soldermask and TT08's
light blue are different pinks and different blues, and a swatch that is a
sample of the board should be that board's colour. Where the sheet has a
colour's name but no hex (TT06's teal silkscreen), the name falls back to
``COLOURS``, and where it has neither the label draws an empty swatch.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from typing import Any

Row = dict[str, Any]

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tt_boards.json")


@lru_cache(maxsize=1)
def load(path: str = DATA) -> Row:
    """The generated document, or an empty one when it is not installed."""
    try:
        with open(path, encoding="utf-8") as f:
            doc: Row = json.load(f)
            return doc
    except (OSError, ValueError):
        return {"asics": {}, "demoboards": {}}


@lru_cache(maxsize=1)
def _demoboard_by_shuttle() -> dict[str, Row]:
    """shuttle -> its demo board row, from each board's "Used by" list."""
    out: dict[str, Row] = {}
    for name, board in sorted(load().get("demoboards", {}).items()):
        for shuttle in board.get("used_by") or ():
            out.setdefault(shuttle, dict(board, id=name))
    return out


def shuttle_boards(shuttle: str | None) -> dict[str, Row | None]:
    """What the sheet knows about `shuttle`'s two boards, as
    ``{"chip": row or None, "demoboard": row or None}``. Both are None for a
    shuttle the sheet does not carry, so a caller can ask without a special
    case."""
    key = "".join((shuttle or "").split()).lower()
    return {"chip": load().get("asics", {}).get(key),
            "demoboard": _demoboard_by_shuttle().get(key)}


def colours(shuttle: str | None, palette: dict[str, str]) -> dict[str, str | None]:
    """The four colours a Tiny Tapeout label paints, as hex or None:
    ``chip``/``chip_silk`` for the carrier and ``demoboard``/
    ``demoboard_silk`` for the board under it, each with the sheet's name
    beside it. `palette` is the name -> hex fallback for a colour the sheet
    names but has no hex for."""
    found = shuttle_boards(shuttle)
    out: dict[str, str | None] = {}
    for role, row in (("chip", found["chip"]), ("demoboard", found["demoboard"])):
        for key, suffix in (("colour", ""), ("silk", "_silk")):
            # Lower case for the words beside the swatch: the label sets
            # every colour that way, and the sheet is of two minds about it
            # ("Light Blue" one row, "Light green" the next).
            name = ((row or {}).get(key) or "").lower() or None
            hexed = (row or {}).get(key + "_hex")
            out[role + suffix] = hexed or palette.get(name or "")
            out[role + suffix + "_name"] = name
    return out


def demoboard_version(shuttle: str | None) -> str | None:
    """The version of the demo board that shipped with `shuttle`'s kit."""
    return (shuttle_boards(shuttle)["demoboard"] or {}).get("version")


def chip_page(shuttle: str | None) -> str | None:
    """The shuttle's page on tinytapeout.com, as the sheet records it."""
    return (shuttle_boards(shuttle)["chip"] or {}).get("chip_page")
